accounts/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('accounts.views',
    url(r'^create/$', 'create_user', name='create'),
    url(r'^profile/$', 'profile', name='profile'),
)

codesmash/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'codesmash.views.home', name='home'),
    url(r'^contact/', include('contact.urls', namespace='contact')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    url(r'^admin/', include(admin.site.urls)),
)

contact/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('contact.views',
    url(r'^$', 'contact_form', name='form'),
)

talks/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required


from talks.views import TalkListView, TalkCreationView, TalkUpdateView


urlpatterns = patterns('talks.views',
    url(r'^$', TalkListView.as_view(), name='index'),
    url(r'^create/$', TalkCreationView.as_view(), name='create'),
    url(r'^edit/(?P<pk>[0-9]+)/$', login_required(TalkUpdateView.as_view()), name='update'),
)

contact/models.py
from django.db import models

# Create your models here.

talks/models.py
from django.db import models


class Talk(models.Model):

    title = models.CharField(max_length=255)

    approved = models.NullBooleanField()
    recording_release = models.BooleanField(default=False)

    outline = models.TextField(blank=True)
    abstract = models.TextField(blank=True)
    notes = models.TextField(blank=True)

    def __str__(self):
        return self.title

    def __unicode__(self):
        return unicode(str(self))

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm


class RegistrationForm(UserCreationForm):

    email = forms.EmailField(required=True, help_text="Required.")

    class Meta(UserCreationForm.Meta):
        fields = ("username", "email")

contact/forms.py
from django import forms


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField()
    sender = forms.EmailField()

talks/forms.py
from django import forms

from talks.models import Talk


class TalkForm(forms.ModelForm):

    class Meta:
        model = Talk
        exclude = ("approved", "location", "time_slot")

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required

from accounts.forms import RegistrationForm
from talks.models import Talk


@login_required
def profile(request):
    return render(request, "accounts/profile.html", {
        'proposals': Talk.objects.for_user(request.user),
    })


def create_user(request):
    form = RegistrationForm(request.POST or None)

    if request.method == "POST" and form.is_valid():
        form.save()

        user = authenticate(username=form.cleaned_data["username"],
                password=form.cleaned_data["password1"])
        login(request, user)

        return redirect("accounts:profile")

    return render(request, "accounts/create.html", {
        "form": form,
    })

codesmash/views.py
from django.shortcuts import render


def home(request):
    """The home page view
    """
    return render(request, "index.html")

contact/views.py
from django.shortcuts import render
from django.core.mail import send_mail

from contact.forms import ContactForm


def contact_form(request):
    form = ContactForm(request.POST or None)

    if request.method == "POST" and form.is_valid():
        send_mail(form.cleaned_data['subject'], form.cleaned_data['message'],
                form.cleaned_data['sender'], ['codesmash@example.com'])

    return render(request, 'contact/form.html', {
        'form': form,
    })

talks/views.py
from django.shortcuts import render

# Create your views here.

templates/accounts/create.html
{% extends "base.html" %}

{% block title %}Codesmash: Register{% endblock %}

{% block content %}
<h1>Register for Codesmash</h1>

<form method="post" action="{% url 'accounts:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register" />
</form>
{% endblock %}

templates/accounts/profile.html
{% extends "base.html" %}
{% load icons %}

{% block title %}Codesmash: Your Profile{% endblock %}

{% block content %}
<h1>Your Profile</h1>
<p>Hello, <b>{{ user.username }}</b>.</p>
<p>Email: <b>{{ user.email }}</b></p>

<h1>Talk Submissions</h1>
<p><a href="{% url 'talks:create' %}">Submit Proposal</a></p>
<table>
    <tr>
        <th>Title</th>
        <th>Type</th>
        <th>Category</th>
        <th>Approved</th>
    </tr>
    {% for proposal in proposals %}
    <tr>
        <td><a href="{% url 'talks:update' proposal.id %}">{{ proposal.title }}</a></td>
        <td>{{ proposal.talk_type }}</td>
        <td>{{ proposal.category }}</td>
        <td>{{ proposal.approved|boolean_icon }}</td>
    {% endfor %}
</table>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}Hello Codesmash{% endblock %}</title>
        <meta name="viewport" content="width=device-width">
    </head>
    <body>
        <style>
            body {
                font-family: sans-serif;
            }

			label {
				font-weight: bold;
			}

			.errorlist {
				color: red;
				font-size: small;
			}
			.helptext {
				display: block;
				font-size: small;
			}
        </style>

        {% block content %}
        {% endblock %}
    </body>
</html>

templates/contact/form.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Codesmash: Contact Us</title>
        <meta name="viewport" content="width=device-width">
    </head>
    <body>
        <h1>Contact Us</h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Contact Us</button>
        </form>
    </body>
</html>

templates/contact/thanks.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Codesmash: Contact Us</title>
        <meta name="viewport" content="width=device-width">
    </head>
    <body>
        <h1>Thanks for contacting us!</h1>
    </body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Hello Codesmash</title>
        <meta name="viewport" content="width=device-width">
    </head>
    <body>
        <h1>Hello Codesmash</h1>
        <p>You've just created your first Django page. Pretty cool, eh?</p>
    </body>
</html>

templates/talks/index.html
{% extends "base.html" %}

{% block content %}
<h1>Talks</h1>
<ul>
    {% for talk in all_talks %}
    <li><h2>{{ talk.title }} ({{ talk.audience_skill_level }})</h2>
        <p><label>Presented In:</label></p>
        <p>{{ talk.location }} at {{ talk.time_slot }}</p>

        <p><label>Presented By:</label></p>
        <ul>
            {% for presenter in talk.proposers.all %}
                {% if presenter.first_name or presenter.last_name %}
                <li><a href="mailto:{{ presenter.email }}">{{ presenter.first_name }} {{ presenter.last_name }}</a></li>
                {% else %}
                <li><a href="mailto:{{ presenter.email }}">{{ presenter.username }}</a></li>
                {% endif %}
            {% endfor %}
        </ul>

        <h3>Abstract</h3>
        <p>{{ talk.abstract }}</p>

        <h3>Outline</h3>
        <p>{{ talk.outline }}</p>
    </li>
    {% endfor %}
</ul>
{% endblock %}

templates/talks/talk_form.html
{% extends "base.html" %}

{% block title %}Codesmash: Submit a Talk Proposal{% endblock %}

{% block content %}
<h1>{% if editing %}Edit{% else %}Submit{% endif %} Talk Proposal</h1>

{% if object.approved %}
<p>Congratulations, this talk has been approved!</p>

<fieldset>
    <legend>Scheduling Details</legend>
    <p>
        <label for="id_time_slot">Time Slot:</label>
        <input type="text" id="id_time_slot" value="{{ object.time_slot }}" disabled size="50"/>
    </p>
    <p>
        <label for="id_location">Location:</label>
        <input type="text" id="id_location" value="{{ object.location }}" disabled />
    </p>
</fieldset>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>Talk Details</legend>
        {{ form.as_p }}
        <input type="submit" value="Save Changes" />
    </fieldset>
</form>
{% endblock %}

templates/talks/talk_list.html
{% extends "base.html" %}

{% block content %}
<h1>Talks</h1>
<ul>
    {% for talk in talk_list %}
    <li><h2>{{ talk.title }} ({{ talk.audience_skill_level }})</h2>
        <p><label>Presented In:</label></p>
        <p>{{ talk.location }} at {{ talk.time_slot }}</p>

        <p><label>Presented By:</label></p>
        <ul>
            {% for presenter in talk.proposers.all %}
                {% if presenter.first_name or presenter.last_name %}
                <li><a href="mailto:{{ presenter.email }}">{{ presenter.first_name }} {{ presenter.last_name }}</a></li>
                {% else %}
                <li><a href="mailto:{{ presenter.email }}">{{ presenter.username }}</a></li>
                {% endif %}
            {% endfor %}
        </ul>

        <h3>Abstract</h3>
        <p>{{ talk.abstract }}</p>

        <h3>Outline</h3>
        <p>{{ talk.outline }}</p>
    </li>
    {% endfor %}
</ul>
{% endblock %}